---
version: '3'
services:
  postgres-master:
    image: bitnami/postgresql:15.2.0
    environment:
      - POSTGRESQL_PASSWORD=postgrespassword
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "5432:5432"
  postgres-slave:
    image: bitnami/postgresql:15.2.0
    environment:
      - POSTGRESQL_PASSWORD=postgrespassword
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master
