---
version: '3'
services:
  postgres-slave:
    image: reedws/pglogical:latest
    environment:
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=data_api
    ports:
      - "5432:5432"
